export enum CmsComponentType {
  HERO_SLIDER = 'HERO_SLIDER',
  FEATURE_ICONS = 'FEATURE_ICONS',
  PRODUCT_GRID = 'PRODUCT_GRID',
  CATEGORY_GRID = 'CATEGORY_GRID',
  PROMO_BANNER = 'PROMO_BANNER',
  BRAND_SLIDER = 'BRAND_SLIDER',
  BLOG_GRID = 'BLOG_GRID',
  VIDEO_SECTION = 'VIDEO_SECTION',
  TESTIMONIALS = 'TESTIMONIALS',
  RICH_TEXT = 'RICH_TEXT',
  CUSTOM_HTML = 'CUSTOM_HTML',
}
